import type { FastifyInstance, FastifyReply } from 'fastify';
import type { QueryResultRow } from 'pg';

import type { Database, FleetSession } from '../auth/auth.types.js';
import { sensitiveRateLimit } from '../plugins/rate-limit.js';
import {
  companyPatchSchema, companySchema, idParamsSchema, locationCreateSchema, locationImportSchema, locationListSchema,
  locationPatchSchema, passwordResetSchema, roleViewSchema, supervisorDriversSchema, userCreateSchema, userLocationsSchema,
  userPatchSchema, userVehicleSchema, vehicleCreateSchema, vehicleListSchema, vehiclePatchSchema
} from './administration.schemas.js';

type Row = QueryResultRow & Record<string, unknown>;
type DbError = { code?: string };

function noStore(reply: FastifyReply): FastifyReply { return reply.header('Cache-Control', 'no-store'); }
function fail(reply: FastifyReply, code: number, error: string, message: string) { return noStore(reply).code(code).send({ error, message }); }
function invalid(reply: FastifyReply) { return fail(reply, 400, 'invalid_request', 'Solicitud inválida.'); }
function forbidden(reply: FastifyReply) { return fail(reply, 403, 'forbidden', 'No tienes permiso para realizar esta acción.'); }
function isSuper(session: FleetSession) { return session.roleCode === 'super_admin'; }
function isAdmin(session: FleetSession) { return session.roleCode === 'admin'; }
function isSupervisor(session: FleetSession) { return session.roleCode === 'supervisor'; }
function canReadCompany(session: FleetSession, companyId: string | null) { return isSuper(session) || (companyId !== null && session.companyId === companyId); }
function canManageCompany(session: FleetSession, companyId: string | null) { return isSuper(session) || (isAdmin(session) && companyId !== null && session.companyId === companyId); }
function canManageUserLocations(session: FleetSession, companyId: string | null) { return isSuper(session) || ((isAdmin(session) || isSupervisor(session)) && companyId !== null && session.companyId === companyId); }
function sessionOr401(session: FleetSession | null, reply: FastifyReply): session is FleetSession { if (session) return true; fail(reply, 401, 'invalid_session', 'Sesión inválida o expirada.'); return false; }
function uniqueError(error: unknown) { return (error as DbError).code === '23505'; }

async function companyExists(database: Database, id: string, activeOnly = false): Promise<boolean> {
  const result = await database.query<Row>(`SELECT id FROM public.empresas WHERE id = $1::uuid${activeOnly ? ' AND activo = true' : ''}`, [id]);
  return result.rowCount === 1;
}
async function companyNameTaken(database: Database, name: string, exceptId?: string): Promise<boolean> {
  const result = await database.query<Row>(
    `SELECT id FROM public.empresas
     WHERE lower(btrim(nombre)) = lower(btrim($1::text))
       ${exceptId ? 'AND id <> $2::uuid' : ''}
     LIMIT 1`,
    exceptId ? [name, exceptId] : [name]
  );
  return result.rowCount === 1;
}
async function user(database: Database, id: string): Promise<Row | undefined> {
  return (await database.query<Row>(`SELECT u.id, u.usuario, u.nombre, u.activo, u.empresa_id, u.rol_id, r.codigo AS rol_codigo FROM public.usuarios u JOIN public.roles r ON r.id = u.rol_id WHERE u.id = $1::uuid`, [id])).rows[0];
}
async function role(database: Database, id: string): Promise<Row | undefined> { return (await database.query<Row>('SELECT id, codigo FROM public.roles WHERE id = $1::uuid AND activo = true', [id])).rows[0]; }
function userResponse(row: Row) { return { id: row.id, usuario: row.usuario, nombre: row.nombre, activo: row.activo, empresa_id: row.empresa_id, empresa_nombre: row.empresa_nombre ?? null, rol_id: row.rol_id, rol: row.rol ?? row.rol_codigo }; }

export function registerAdministrationRoutes(app: FastifyInstance, database: Database): void {
  app.get('/api/companies', { preHandler: app.requireFleetSession }, async (request, reply) => {
    if (!sessionOr401(request.fleetSession, reply)) return;
    const s = request.fleetSession;
    if (!isSuper(s) && !s.companyId) return forbidden(reply);
    const result = await database.query<Row>(`SELECT id, nombre, activo, created_at, updated_at FROM public.empresas ${isSuper(s) ? '' : 'WHERE id = $1::uuid'} ORDER BY nombre`, isSuper(s) ? [] : [s.companyId]);
    return noStore(reply).send({ companies: result.rows });
  });
  app.post('/api/companies', { preHandler: app.requireFleetSession }, async (request, reply) => {
    const body = companySchema.safeParse(request.body); if (!body.success) return invalid(reply);
    if (!sessionOr401(request.fleetSession, reply)) return; if (!isSuper(request.fleetSession)) return forbidden(reply);
    if (await companyNameTaken(database, body.data.nombre)) return fail(reply, 409, 'conflict', 'Ya existe una empresa con ese nombre.');
    try { const result = await database.query<Row>('INSERT INTO public.empresas (nombre, activo) VALUES ($1::text, $2::boolean) RETURNING id, nombre, activo, created_at, updated_at', [body.data.nombre, body.data.activo ?? true]); return noStore(reply).code(201).send({ company: result.rows[0] }); }
    catch (error) { if (uniqueError(error)) return fail(reply, 409, 'conflict', 'Ya existe una empresa con ese nombre.'); throw error; }
  });
  app.patch('/api/companies/:id', { preHandler: app.requireFleetSession }, async (request, reply) => {
    const params = idParamsSchema.safeParse(request.params), body = companyPatchSchema.safeParse(request.body); if (!params.success || !body.success) return invalid(reply);
    if (!sessionOr401(request.fleetSession, reply)) return; if (!isSuper(request.fleetSession)) return forbidden(reply);
    if (body.data.nombre !== undefined && await companyNameTaken(database, body.data.nombre, params.data.id)) return fail(reply, 409, 'conflict', 'Ya existe una empresa con ese nombre.');
    const values: unknown[] = []; const set: string[] = [];
    if (body.data.nombre !== undefined) { values.push(body.data.nombre); set.push(`nombre = $${values.length}::text`); } if (body.data.activo !== undefined) { values.push(body.data.activo); set.push(`activo = $${values.length}::boolean`); }
    values.push(params.data.id);
    try { const result = await database.query<Row>(`UPDATE public.empresas SET ${set.join(', ')}, updated_at = now() WHERE id = $${values.length}::uuid RETURNING id, nombre, activo, created_at, updated_at`, values); if (!result.rows[0]) return fail(reply, 404, 'not_found', 'Empresa no encontrada.'); return noStore(reply).send({ company: result.rows[0] }); }
    catch (error) { if (uniqueError(error)) return fail(reply, 409, 'conflict', 'Ya existe una empresa con ese nombre.'); throw error; }
  });

  app.get('/api/locations', { preHandler: app.requireFleetSession }, async (request, reply) => {
    const query = locationListSchema.safeParse(request.query); if (!query.success) return invalid(reply); if (!sessionOr401(request.fleetSession, reply)) return; const s = request.fleetSession;
    const companyId = isSuper(s) ? query.data.empresa_id : s.companyId; if (!canReadCompany(s, companyId ?? null)) return forbidden(reply);
    const result = await database.query<Row>(`SELECT l.id,l.empresa_id,l.nombre,l.direccion,l.codigo,l.descripcion,l.latitud,l.longitud,l.radio_metros,l.activo,l.created_at,l.updated_at,e.nombre AS empresa_nombre FROM public.locales l JOIN public.empresas e ON e.id=l.empresa_id ${companyId ? 'WHERE l.empresa_id=$1::uuid' : ''} ORDER BY l.nombre`, companyId ? [companyId] : []);
    return noStore(reply).send({ locations: result.rows });
  });
  app.post('/api/locations', { preHandler: app.requireFleetSession }, async (request, reply) => {
    const body = locationCreateSchema.safeParse(request.body); if (!body.success) return invalid(reply); if (!sessionOr401(request.fleetSession, reply)) return; if (!canManageCompany(request.fleetSession, body.data.empresa_id)) return forbidden(reply); if (!await companyExists(database, body.data.empresa_id, true)) return fail(reply, 404, 'not_found', 'Empresa no encontrada o inactiva.');
    const d = body.data; const result = await database.query<Row>('INSERT INTO public.locales (empresa_id,nombre,direccion,codigo,descripcion,latitud,longitud,radio_metros,activo) VALUES ($1::uuid,$2::text,$3::text,$4::text,$5::text,$6::double precision,$7::double precision,$8::double precision,$9::boolean) RETURNING *', [d.empresa_id,d.nombre,d.direccion ?? null,d.codigo ?? null,d.descripcion ?? null,d.latitud,d.longitud,d.radio_metros ?? 100,d.activo ?? true]); return noStore(reply).code(201).send({ location: result.rows[0] });
  });
  app.patch('/api/locations/:id', { preHandler: app.requireFleetSession }, async (request, reply) => {
    const params=idParamsSchema.safeParse(request.params), body=locationPatchSchema.safeParse(request.body); if(!params.success||!body.success)return invalid(reply); if(!sessionOr401(request.fleetSession,reply))return; const current=(await database.query<Row>('SELECT empresa_id FROM public.locales WHERE id=$1::uuid',[params.data.id])).rows[0]; if(!current)return fail(reply,404,'not_found','Local no encontrado.'); const target=body.data.empresa_id??String(current.empresa_id); if(!canManageCompany(request.fleetSession,current.empresa_id as string)||!canManageCompany(request.fleetSession,target))return forbidden(reply); if(body.data.empresa_id&&!await companyExists(database,target,true))return fail(reply,404,'not_found','Empresa no encontrada o inactiva.'); const columns: Record<string,string>={empresa_id:'uuid',nombre:'text',direccion:'text',codigo:'text',descripcion:'text',latitud:'double precision',longitud:'double precision',radio_metros:'double precision',activo:'boolean'}; const values:unknown[]=[]; const set:string[]=[]; for(const [key,type] of Object.entries(columns)){const value=(body.data as Record<string,unknown>)[key];if(value!==undefined){values.push(value);set.push(`${key}=$${values.length}::${type}`);}} values.push(params.data.id); const result=await database.query<Row>(`UPDATE public.locales SET ${set.join(', ')},updated_at=now() WHERE id=$${values.length}::uuid RETURNING *`,values); return noStore(reply).send({location:result.rows[0]});
  });
  app.post('/api/locations/import', { preHandler: app.requireFleetSession }, async (request, reply) => {
    const body=locationImportSchema.safeParse(request.body);if(!body.success)return invalid(reply);if(!sessionOr401(request.fleetSession,reply))return;const s=request.fleetSession;if(!isSuper(s)&&!isAdmin(s))return forbidden(reply);const companyId=isSuper(s)?body.data.empresa_id:s.companyId;if(!companyId||!canManageCompany(s,companyId)||!await companyExists(database,companyId,true))return forbidden(reply);const result=await database.query<Row>('SELECT public.fleet_control_import_locations($1::uuid,$2::jsonb) AS result',[companyId,JSON.stringify(body.data.locations)]);const output=result.rows[0]?.result as { errors?: unknown[] } | undefined;if(output?.errors?.length)return noStore(reply).code(400).send(output);return noStore(reply).code(201).send(output);
  });

  app.get('/api/users', { preHandler: app.requireFleetSession }, async (request, reply) => { if(!sessionOr401(request.fleetSession,reply))return;const s=request.fleetSession;if(!isSuper(s)&&!isAdmin(s)&&!isSupervisor(s))return forbidden(reply);const result=await database.query<Row>(`SELECT u.id,u.usuario,u.nombre,u.activo,u.empresa_id,u.rol_id,e.nombre AS empresa_nombre,r.codigo AS rol FROM public.usuarios u JOIN public.roles r ON r.id=u.rol_id LEFT JOIN public.empresas e ON e.id=u.empresa_id ${isSuper(s)?'':'WHERE u.empresa_id=$1::uuid'} ORDER BY u.nombre`,isSuper(s)?[]:[s.companyId]);return noStore(reply).send({users:result.rows.map(userResponse)}); });
  app.post('/api/users', { preHandler: app.requireFleetSession }, async (request, reply) => { const body=userCreateSchema.safeParse(request.body);if(!body.success)return invalid(reply);if(!sessionOr401(request.fleetSession,reply))return;const s=request.fleetSession;if(!isSuper(s)&&!isAdmin(s))return forbidden(reply);const r=await role(database,body.data.rol_id);if(!r)return fail(reply,400,'invalid_request','Rol inválido.');const companyId=body.data.empresa_id??null;if(!isSuper(s)&&(!companyId||!canManageCompany(s,companyId)||(r.codigo==='super_admin')))return forbidden(reply);if(companyId&&!await companyExists(database,companyId))return fail(reply,404,'not_found','Empresa no encontrada.');try{const created=await database.query<Row>('SELECT public.fleet_control_create_usuario($1::text,$2::text,$3::text,$4::uuid,$5::uuid,$6::boolean) AS id',[body.data.nombre,body.data.usuario,body.data.password,companyId,body.data.rol_id,body.data.activo??true]);const id=created.rows[0]?.id as string;const result=await database.query<Row>('SELECT u.id,u.usuario,u.nombre,u.activo,u.empresa_id,u.rol_id,e.nombre AS empresa_nombre,r.codigo AS rol FROM public.usuarios u JOIN public.roles r ON r.id=u.rol_id LEFT JOIN public.empresas e ON e.id=u.empresa_id WHERE u.id=$1::uuid',[id]);return noStore(reply).code(201).send({user:userResponse(result.rows[0])});}catch(error){if(uniqueError(error))return fail(reply,409,'conflict','El usuario ya existe.');throw error;} });
  app.patch('/api/users/:id', { preHandler: app.requireFleetSession }, async (request, reply) => { const params=idParamsSchema.safeParse(request.params),body=userPatchSchema.safeParse(request.body);if(!params.success||!body.success)return invalid(reply);if(!sessionOr401(request.fleetSession,reply))return;const s=request.fleetSession;if(!isSuper(s)&&!isAdmin(s))return forbidden(reply);const current=await user(database,params.data.id);if(!current)return fail(reply,404,'not_found','Usuario no encontrado.');const target=body.data.empresa_id===undefined?current.empresa_id as string|null:body.data.empresa_id;if(!canManageCompany(s,current.empresa_id as string|null)||!canManageCompany(s,target))return forbidden(reply);if(body.data.rol_id){const r=await role(database,body.data.rol_id);if(!r)return fail(reply,400,'invalid_request','Rol inválido.');if(!isSuper(s)&&r.codigo==='super_admin')return forbidden(reply);}if(target&&!await companyExists(database,target))return fail(reply,404,'not_found','Empresa no encontrada.');const columns:Record<string,string>={nombre:'text',usuario:'text',empresa_id:'uuid',rol_id:'uuid',activo:'boolean'};const values:unknown[]=[];const set:string[]=[];for(const [key,type] of Object.entries(columns)){const value=(body.data as Record<string,unknown>)[key];if(value!==undefined){values.push(value);set.push(`${key}=$${values.length}::${type}`)}}values.push(params.data.id);try{const result=await database.query<Row>(`UPDATE public.usuarios SET ${set.join(', ')} WHERE id=$${values.length}::uuid RETURNING id,usuario,nombre,activo,empresa_id,rol_id`,values);return noStore(reply).send({user:userResponse(result.rows[0])});}catch(error){if(uniqueError(error))return fail(reply,409,'conflict','El usuario ya existe.');throw error;} });
  app.post('/api/users/:id/password-reset', { preHandler: app.requireFleetSession, config: sensitiveRateLimit }, async (request, reply) => {const params=idParamsSchema.safeParse(request.params),body=passwordResetSchema.safeParse(request.body);if(!params.success||!body.success)return invalid(reply);if(!sessionOr401(request.fleetSession,reply))return;const target=await user(database,params.data.id);if(!target)return fail(reply,404,'not_found','Usuario no encontrado.');const s=request.fleetSession;if(s.userId!==params.data.id&&!isSuper(s)&&!(isAdmin(s)&&s.companyId===target.empresa_id))return forbidden(reply);await database.query('SELECT public.fleet_control_set_usuario_password($1::uuid,$2::text)',[params.data.id,body.data.password]);return noStore(reply).send({success:true});});
  app.get('/api/roles', { preHandler: app.requireFleetSession }, async (request, reply) => {if(!sessionOr401(request.fleetSession,reply))return;if(!isSuper(request.fleetSession))return forbidden(reply);const result=await database.query<Row>('SELECT id,codigo,nombre,descripcion,nivel,activo FROM public.roles ORDER BY nivel,codigo');return noStore(reply).send({roles:result.rows});});

  app.get('/api/vehicles', { preHandler: app.requireFleetSession }, async (request, reply) => {const query=vehicleListSchema.safeParse(request.query);if(!query.success)return invalid(reply);if(!sessionOr401(request.fleetSession,reply))return;const s=request.fleetSession;if(!isSuper(s)&&!isAdmin(s)&&!isSupervisor(s))return forbidden(reply);const companyId=isSuper(s)?query.data.empresa_id:s.companyId;if(!canReadCompany(s,companyId??null))return forbidden(reply);const result=await database.query<Row>(`SELECT v.*,e.nombre AS empresa_nombre FROM public.vehiculos v JOIN public.empresas e ON e.id=v.empresa_id ${companyId?'WHERE v.empresa_id=$1::uuid':''} ORDER BY v.patente`,companyId?[companyId]:[]);return noStore(reply).send({vehicles:result.rows});});
  app.post('/api/vehicles', { preHandler: app.requireFleetSession }, async (request, reply) => {const body=vehicleCreateSchema.safeParse(request.body);if(!body.success)return invalid(reply);if(!sessionOr401(request.fleetSession,reply))return;if(!canManageCompany(request.fleetSession,body.data.empresa_id))return forbidden(reply);if(!await companyExists(database,body.data.empresa_id,true))return fail(reply,404,'not_found','Empresa no encontrada o inactiva.');const d=body.data;try{const result=await database.query<Row>('INSERT INTO public.vehiculos (empresa_id,patente,marca,modelo,descripcion,anio,tipo_vehiculo,activo) VALUES ($1::uuid,$2::text,$3::text,$4::text,$5::text,$6::int,$7::text,$8::boolean) RETURNING *',[d.empresa_id,d.patente,d.marca??null,d.modelo??null,d.descripcion??null,d.anio??null,d.tipo_vehiculo??null,d.activo??true]);return noStore(reply).code(201).send({vehicle:result.rows[0]});}catch(error){if(uniqueError(error))return fail(reply,409,'conflict','Ya existe un vehículo con esa patente.');throw error;}});
  app.patch('/api/vehicles/:id', { preHandler: app.requireFleetSession }, async (request, reply) => {const params=idParamsSchema.safeParse(request.params),body=vehiclePatchSchema.safeParse(request.body);if(!params.success||!body.success)return invalid(reply);if(!sessionOr401(request.fleetSession,reply))return;const current=(await database.query<Row>('SELECT empresa_id FROM public.vehiculos WHERE id=$1::uuid',[params.data.id])).rows[0];if(!current)return fail(reply,404,'not_found','Vehículo no encontrado.');const target=body.data.empresa_id??current.empresa_id as string;if(!canManageCompany(request.fleetSession,current.empresa_id as string)||!canManageCompany(request.fleetSession,target))return forbidden(reply);if(body.data.empresa_id&&!await companyExists(database,target,true))return fail(reply,404,'not_found','Empresa no encontrada o inactiva.');const columns:Record<string,string>={empresa_id:'uuid',patente:'text',marca:'text',modelo:'text',descripcion:'text',anio:'int',tipo_vehiculo:'text',activo:'boolean'};const values:unknown[]=[];const set:string[]=[];for(const [key,type] of Object.entries(columns)){const value=(body.data as Record<string,unknown>)[key];if(value!==undefined){values.push(value);set.push(`${key}=$${values.length}::${type}`)}}values.push(params.data.id);try{const result=await database.query<Row>(`UPDATE public.vehiculos SET ${set.join(', ')},updated_at=now() WHERE id=$${values.length}::uuid RETURNING *`,values);return noStore(reply).send({vehicle:result.rows[0]});}catch(error){if(uniqueError(error))return fail(reply,409,'conflict','Ya existe un vehículo con esa patente.');throw error;}});

  app.get('/api/users/:id/locations', { preHandler: app.requireFleetSession }, async (request,reply)=>{const params=idParamsSchema.safeParse(request.params);if(!params.success)return invalid(reply);if(!sessionOr401(request.fleetSession,reply))return;const target=await user(database,params.data.id);if(!target)return fail(reply,404,'not_found','Usuario no encontrado.');if(!canManageUserLocations(request.fleetSession,target.empresa_id as string|null))return forbidden(reply);const result=await database.query<Row>(`SELECT l.id,l.empresa_id,l.nombre,l.direccion,l.activo,(ul.usuario_id IS NOT NULL) AS assigned FROM public.locales l LEFT JOIN public.usuario_locales ul ON ul.local_id=l.id AND ul.usuario_id=$1::uuid WHERE l.empresa_id=$2::uuid ORDER BY l.nombre`,[params.data.id,target.empresa_id]);return noStore(reply).send({user:userResponse(target),locations:result.rows});});
  app.put('/api/users/:id/locations', { preHandler: app.requireFleetSession }, async (request,reply)=>{const params=idParamsSchema.safeParse(request.params),body=userLocationsSchema.safeParse(request.body);if(!params.success||!body.success)return invalid(reply);if(!sessionOr401(request.fleetSession,reply))return;const target=await user(database,params.data.id);if(!target)return fail(reply,404,'not_found','Usuario no encontrado.');if(!canManageUserLocations(request.fleetSession,target.empresa_id as string|null))return forbidden(reply);if(body.data.location_ids.length){const valid=await database.query<Row>('SELECT id FROM public.locales WHERE empresa_id=$1::uuid AND id = ANY($2::uuid[])',[target.empresa_id,body.data.location_ids]);if(valid.rowCount!==body.data.location_ids.length)return fail(reply,400,'invalid_request','Uno o más locales no pertenecen a la empresa.');}await database.query('SELECT public.fleet_control_set_user_locations($1::uuid,$2::uuid[])',[params.data.id,body.data.location_ids]);return noStore(reply).send({success:true,location_ids:body.data.location_ids});});
  app.get('/api/me/locations', { preHandler: app.requireFleetSession }, async (request,reply)=>{if(!sessionOr401(request.fleetSession,reply))return;const result=await database.query<Row>('SELECT l.id,l.empresa_id,l.codigo,l.nombre,l.direccion,l.descripcion,l.latitud,l.longitud,l.radio_metros,l.activo FROM public.usuario_locales ul JOIN public.locales l ON l.id=ul.local_id WHERE ul.usuario_id=$1::uuid AND l.activo=true ORDER BY l.nombre',[request.fleetSession.userId]);return noStore(reply).send({locations:result.rows});});

  app.get('/api/users/:id/vehicle', { preHandler: app.requireFleetSession }, async (request,reply)=>{const params=idParamsSchema.safeParse(request.params);if(!params.success)return invalid(reply);if(!sessionOr401(request.fleetSession,reply))return;const s=request.fleetSession;if(!isSuper(s)&&!isAdmin(s)&&!isSupervisor(s))return forbidden(reply);const target=await user(database,params.data.id);if(!target||target.rol_codigo!=='chofer')return fail(reply,404,'not_found','Chofer no encontrado.');if(!canReadCompany(s,target.empresa_id as string|null))return forbidden(reply);const [assigned,vehicles]=await Promise.all([database.query<Row>('SELECT uv.usuario_id,uv.vehiculo_id,v.* FROM public.usuario_vehiculos uv JOIN public.vehiculos v ON v.id=uv.vehiculo_id WHERE uv.usuario_id=$1::uuid',[params.data.id]),database.query<Row>('SELECT * FROM public.vehiculos WHERE empresa_id=$1::uuid AND activo=true ORDER BY patente',[target.empresa_id])]);return noStore(reply).send({user_vehicle:assigned.rows[0]??null,vehicles:vehicles.rows});});
  app.patch('/api/users/:id/vehicle', { preHandler: app.requireFleetSession }, async (request,reply)=>{const params=idParamsSchema.safeParse(request.params),body=userVehicleSchema.safeParse(request.body);if(!params.success||!body.success)return invalid(reply);if(!sessionOr401(request.fleetSession,reply))return;const target=await user(database,params.data.id);if(!target||target.rol_codigo!=='chofer')return fail(reply,404,'not_found','Chofer no encontrado.');if(!canManageCompany(request.fleetSession,target.empresa_id as string|null))return forbidden(reply);if(body.data.vehicle_id){const vehicle=(await database.query<Row>('SELECT id FROM public.vehiculos WHERE id=$1::uuid AND empresa_id=$2::uuid',[body.data.vehicle_id,target.empresa_id])).rows[0];if(!vehicle)return fail(reply,400,'invalid_request','El vehículo no pertenece a la empresa.');}const result=await database.query<Row>('SELECT (public.fleet_control_set_user_vehicle($1::uuid,$2::uuid)).*',[params.data.id,body.data.vehicle_id]);return noStore(reply).send({user_vehicle:result.rows[0]??null});});

  app.get('/api/supervisors/:id/drivers', { preHandler: app.requireFleetSession }, async (request,reply)=>{const params=idParamsSchema.safeParse(request.params);if(!params.success)return invalid(reply);if(!sessionOr401(request.fleetSession,reply))return;const s=request.fleetSession;if(!isSuper(s)&&!isAdmin(s))return forbidden(reply);const supervisor=await user(database,params.data.id);if(!supervisor||supervisor.rol_codigo!=='supervisor'||!canManageCompany(s,supervisor.empresa_id as string|null))return forbidden(reply);const drivers=await database.query<Row>(`SELECT u.id,u.usuario,u.nombre,(sc.supervisor_usuario_id IS NOT NULL) AS assigned FROM public.usuarios u JOIN public.roles r ON r.id=u.rol_id LEFT JOIN public.supervisor_choferes sc ON sc.chofer_usuario_id=u.id AND sc.supervisor_usuario_id=$1::uuid WHERE u.empresa_id=$2::uuid AND u.activo=true AND r.codigo='chofer' ORDER BY u.nombre`,[params.data.id,supervisor.empresa_id]);const assigned=drivers.rows.filter((x)=>x.assigned).map((x)=>x.id);return noStore(reply).send({supervisor:userResponse(supervisor),assigned_driver_ids:assigned,assigned_drivers:drivers.rows.filter((x)=>x.assigned),available_drivers:drivers.rows.filter((x)=>!x.assigned)});});
  app.put('/api/supervisors/:id/drivers', { preHandler: app.requireFleetSession }, async (request,reply)=>{const params=idParamsSchema.safeParse(request.params),body=supervisorDriversSchema.safeParse(request.body);if(!params.success||!body.success)return invalid(reply);if(!sessionOr401(request.fleetSession,reply))return;const s=request.fleetSession;if(!isSuper(s)&&!isAdmin(s))return forbidden(reply);const supervisor=await user(database,params.data.id);if(!supervisor||supervisor.rol_codigo!=='supervisor'||!canManageCompany(s,supervisor.empresa_id as string|null))return forbidden(reply);if(body.data.driver_user_ids.length){const valid=await database.query<Row>(`SELECT u.id FROM public.usuarios u JOIN public.roles r ON r.id=u.rol_id WHERE u.id=ANY($1::uuid[]) AND u.empresa_id=$2::uuid AND u.activo=true AND r.codigo='chofer'`,[body.data.driver_user_ids,supervisor.empresa_id]);if(valid.rowCount!==body.data.driver_user_ids.length)return fail(reply,400,'invalid_request','Uno o más choferes no pertenecen a la empresa.');}await database.query('SELECT public.fleet_control_set_supervisor_choferes($1::uuid,$2::uuid[])',[params.data.id,body.data.driver_user_ids]);return noStore(reply).send({supervisor_user_id:params.data.id,driver_user_ids:body.data.driver_user_ids});});

  app.get('/api/role-views', { preHandler: app.requireFleetSession }, async (request,reply)=>{if(!sessionOr401(request.fleetSession,reply))return;if(!isSuper(request.fleetSession))return forbidden(reply);const [roles,views,assignments]=await Promise.all([database.query<Row>(`SELECT id,codigo,nombre FROM public.roles WHERE codigo=ANY($1::text[]) ORDER BY codigo`,[['super_admin','admin','supervisor','chofer','user','local']]),database.query<Row>('SELECT id,codigo,nombre,descripcion,ruta,icono,orden,activo FROM public.app_views ORDER BY orden,codigo'),database.query<Row>('SELECT r.codigo AS role_code,v.codigo AS view_code,rv.visible FROM public.role_views rv JOIN public.roles r ON r.id=rv.role_id JOIN public.app_views v ON v.id=rv.view_id')]);return noStore(reply).send({roles:roles.rows,views:views.rows,role_views:assignments.rows});});
  app.patch('/api/role-views', { preHandler: app.requireFleetSession }, async (request,reply)=>{const body=roleViewSchema.safeParse(request.body);if(!body.success)return invalid(reply);if(!sessionOr401(request.fleetSession,reply))return;if(!isSuper(request.fleetSession))return forbidden(reply);const d=body.data;if(!d.visible&&(['home','settings'].includes(d.view_code)||(d.role_code==='super_admin'&&d.view_code==='role_views_management')))return fail(reply,400,'invalid_request','Esa vista no puede ocultarse.');const roleRow=(await database.query<Row>('SELECT id FROM public.roles WHERE codigo=$1::text',[d.role_code])).rows[0],viewRow=(await database.query<Row>('SELECT id FROM public.app_views WHERE codigo=$1::text',[d.view_code])).rows[0];if(!roleRow||!viewRow)return fail(reply,404,'not_found','Rol o vista no encontrados.');const result=await database.query<Row>('INSERT INTO public.role_views (role_id,view_id,visible) VALUES ($1::uuid,$2::uuid,$3::boolean) ON CONFLICT (role_id,view_id) DO UPDATE SET visible=EXCLUDED.visible,updated_at=now() RETURNING id,role_id,view_id,visible',[roleRow.id,viewRow.id,d.visible]);return noStore(reply).send({role_view:{...result.rows[0],role_code:d.role_code,view_code:d.view_code}});});
}
